#!/bin/bash
# ENV=$1
# TODO make env configurable
TERRAFORM_OUTPUT_FILE="./amideploy/configuration/cadc-output.json"
AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME=$(jq -r '.airflow_server_ip.value' $TERRAFORM_OUTPUT_FILE)
AMI_CONNECT__AIRFLOW_SERVER_USERNAME=ec2-user
AMI_CONNECT__AIRFLOW_SERVER_PEM=amideploy/configuration/cadc-airflow-key.pem

AMI_CONNECT__AIRFLOW_METASTORE_HOST=$(jq -r '.airflow_db_host.value' $TERRAFORM_OUTPUT_FILE)
AMI_CONNECT__AIRFLOW_METASTORE_PASSWORD=$(jq -r '.airflow_db_password.value' $TERRAFORM_OUTPUT_FILE)
AMI_CONNECT__AIRFLOW_METASTORE_CONN=postgresql+psycopg2://airflow_user:$AMI_CONNECT__AIRFLOW_METASTORE_PASSWORD@$AMI_CONNECT__AIRFLOW_METASTORE_HOST/airflow_db

REMOTE_DIR="./build"

echo "Deploying to Airflow server at $AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME:$REMOTE_DIR using PEM $AMI_CONNECT__AIRFLOW_SERVER_PEM"

echo "Copying deployment files to Airflow server..."
ssh -i $AMI_CONNECT__AIRFLOW_SERVER_PEM $AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME "mkdir -p ${REMOTE_DIR}"
scp -i $AMI_CONNECT__AIRFLOW_SERVER_PEM ./amideploy/deploy/Dockerfile "$AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME:$REMOTE_DIR/"
scp -i $AMI_CONNECT__AIRFLOW_SERVER_PEM ./amideploy/deploy/docker-compose.yml "$AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME:$REMOTE_DIR/"
scp -i $AMI_CONNECT__AIRFLOW_SERVER_PEM ./amideploy/deploy/remote-deploy.sh "$AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME:$REMOTE_DIR/"
[ -f "./known-hosts" ] && scp -i $AMI_CONNECT__AIRFLOW_SERVER_PEM ./known-hosts "$AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME:$REMOTE_DIR/"

# TODO make neptune crap configurable, make it pull from GitHub
ssh -i $AMI_CONNECT__AIRFLOW_SERVER_PEM $AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME "cp -r /home/ec2-user/neptune ${REMOTE_DIR}/"

echo "Executing deployment script on Airflow server..."
ssh -i $AMI_CONNECT__AIRFLOW_SERVER_PEM $AMI_CONNECT__AIRFLOW_SERVER_USERNAME@$AMI_CONNECT__AIRFLOW_SERVER_HOSTNAME "AMI_CONNECT__AIRFLOW_METASTORE_CONN=$AMI_CONNECT__AIRFLOW_METASTORE_CONN bash $REMOTE_DIR/remote-deploy.sh"
